services:
  - type: web
    name: cafe-wifi
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cafe-wifi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: cafe-wifi-db
    databaseName: cafe_wifi
    user: cafe_wifi_user 